### PR TITLE
Adding Classify Learning data source

### PR DESCRIPTION
**Pull request by rveltonCL**

### CODE REVIEW

**Comment by rveltonCL** [comment]
@googlebot I signed it!

**Comment by rveltonCL** [comment]
@googlebot I signed it!

**Comment by rveltonCL** [comment]
@googlebot I consent.

**Comment by RobertVelton** [comment]
@googlebot I signed it!

**Comment by RobertVelton** [comment]
@googlebot I consent.

**Review by pfrisella — APPROVED** [review]
LGTM. Thanks for adding!

**Pull request merged**
