### PR TITLE
Add source/organisation for intelliAd Performance Marketing Suite GDS Connector 

### PR DESCRIPTION
**Pull request by ikacem**

### CODE REVIEW

**Comment by ikacem** [comment]
I signed it!

**Comment by ikacem** [comment]
I signed it!

**Comment by ikacem** [comment]
Is there any further steps required to accept the pull request!?

**Comment by vkavitska** [comment]
Hello. Can you tell us what other steps we need to do to accept the pull request? Thank's!

**Comment by pfrisella** [comment]
You need to resolve the CLA issue (which is out of my control since it is an automated process)
If you want to check which email is associated with the commits you can view the patch file by adding .patch to the pull request URL: https://github.com/googledatastudio/ds-data-registry/pull/141.patch

I can quickly tell you have an issue, the From email is using @users.noreply.github.com. You need to make sure the from email is associated with the email that has signed the CLA so the automated check can confirm.

Also, the "What to do if you already signed the CLA" section is helpful in troubleshooting this issue.

**Pull request merged**
