### PR TITLE
Xero

### PR DESCRIPTION
**Pull request by kielllll**
Hi team! I have added a source and organization for Xero. Please advise if changes are needed. Thanks!

### CODE REVIEW

**Comment by kielllll** [comment]
@googlebot I signed it!

**Comment by kielllll** [comment]
@googlebot I signed it!

**Comment by kielllll** [comment]
Updated the name attribute - please review @pfrisella . Thanks!

**Review by pfrisella — APPROVED** [review]
LGTM. Thanks for adding!

**Pull request merged**
