### PR TITLE
Create branch.json for Organization

### PR DESCRIPTION
**Pull request by harsh-branch**

### CODE REVIEW

**Comment by harsh-branch** [comment]
@AnuFeb Can you please help review and merge this

**Review by AnuFeb — APPROVED** [review]
LGTM, Thanks for adding

**Comment by AnuFeb** [comment]
Could you please check CLA & then update the branch. I will merge the changes.

**Comment by harsh-branch** [comment]
Done!

**Review by AnuFeb — APPROVED** [review]
LGTM, Thanks for Adding!

**Comment by AnuFeb** [comment]
Could you please update the branch, I will merge the change.

**Comment by harsh-branch** [comment]
Updated the branch. @AnuFeb requesting you to merge this PR.

**Pull request merged**
