### PR TITLE
Add Hiplatform organization and source

### PR DESCRIPTION
**Pull request by alexsandercamargo**

### CODE REVIEW

**Comment by alexsandercamargo** [comment]
@googlebot I signed it!

**Comment by alexsandercamargo** [comment]
@googlebot I signed it!

**Comment by alexsandercamargohi** [comment]
@googlebot I signed it!

**Comment by alexsandercamargohi** [comment]
@googlebot I consent.

**Review by pfrisella — APPROVED** [review]
LGTM. Thanks for adding!

**Pull request merged**
