### PR TITLE
Add pricerunner-api.json

### PR DESCRIPTION
**Pull request by PricerunnerGoogleDataStudio**

### CODE REVIEW

**Comment by PricerunnerGoogleDataStudio** [comment]
@googlebot I signed it!

**Comment by PricerunnerGoogleDataStudio** [comment]
@googlebot I signed it!

**Comment by PricerunnerGoogleDataStudio** [comment]
@googlebot I signed it!

**Review by pfrisella — CHANGES_REQUESTED** [review]
Is this any different than the existing PriceRunner source? It looks the same to me. https://github.com/googledatastudio/ds-data-registry/blob/master/sources/pricerunner.json

**Comment by PricerunnerGoogleDataStudio** [comment]
> Is this any different than the existing PriceRunner source? It looks the same to me. https://github.com/googledatastudio/ds-data-registry/blob/master/sources/pricerunner.json

The existing source is not developed by us at PriceRunner but a third party (funnel.io) who has integrated against our service using web scraping technology. This connector uses our supported API and will be maintained by us at PriceRunner.

**Review by PricerunnerGoogleDataStudio — COMMENTED** [review]
The existing source is not developed by us at PriceRunner but a third party (funnel.io) who has integrated against our service using web scraping technology. This connector uses our supported API and will be maintained by us at PriceRunner.

**Comment by pfrisella** [comment]
The source definition is independent of connector, it simply describes a data source, not a connector. For example, there is a single GOOGLE_ANALYTICS source but there are multiple connectors for Data Studio that fetch Google Analytics data and. They all use same source ID from this registry (GOOGLE_ANALYTICS) and there isn't a different source definition in the registry for each connector. 

I suggest you use the existing source ([PRICERUNNER](https://github.com/googledatastudio/ds-data-registry/blob/master/sources/pricerunner.json)). Feel free to send a pull request to update that existing source to correct any errors and perhaps provide a different icon url.

**Comment by PricerunnerGoogleDataStudio** [comment]
> The source definition is independent of connector, it simply describes a data source, not a connector. For example, there is a single GOOGLE_ANALYTICS source but there are multiple connectors for Data Studio that fetch Google Analytics data and. They all use same source ID from this registry (GOOGLE_ANALYTICS) and there isn't a different source definition in the registry for each connector.
> 
> I suggest you use the existing source ([PRICERUNNER](https://github.com/googledatastudio/ds-data-registry/blob/master/sources/pricerunner.json)). Feel free to send a pull request to update that existing source to correct any errors and perhaps provide a different icon url.

I have now updated the existing pricerunner source.

**Review by pfrisella — APPROVED** [review]
LGTM. Thanks for making the update!

**Pull request merged**
