### PR TITLE
add source and organization for HTLExec data aggregation and analytic…

### PR DESCRIPTION
**Pull request by craiget**
Add source and organization for HTLExec data aggregation and analytics platform, in order to create a Community Connector

### CODE REVIEW

**Review by mendozamedina — APPROVED** [review]
LGTM

**Comment by craiget** [comment]
Hi @mendozamedina, are any additional steps required to get this PR merged, now that it has been approved? Thanks!

**Comment by mendozamedina** [comment]
Hello,
I have reviewed and approved your PR, but your branch is out-of-date with
the base branch, thus I can't merge it.
Please update your branch and then I will merge your code.

Thank you

**Comment by craiget** [comment]
Ah, understood, thanks @mendozamedina

**Pull request merged**
