### PR TITLE
Eulerian Analytics

### PR DESCRIPTION
**Pull request by matjmat**

### CODE REVIEW

**Review by pfrisella — COMMENTED** [review]
This formatting isn't necessary. If you want to format, run prettier as recommended in step #3: https://github.com/googledatastudio/ds-data-registry#add-a-source

**Comment by matjmat** [comment]
hi @pfrisella is it ok now ? do we need to do some other modifications ? Thanks.

**Comment by pfrisella** [comment]
I'm not sure what you're asking for? Your PR #572 was already merged into the master branch last week. What else do you need?

**Comment by matjmat** [comment]
ok sorry about the confusion, the 572 PR is ok, this one can be closed.

**Pull request closed without merging**
