### PR TITLE
new organization and source for Google DataStudio connectors

### PR DESCRIPTION
**Pull request by AJavierSanchez**
Creating Soluciones Informaticas Globales SA organization and SIG_ETL source

### CODE REVIEW

**Comment by AJavierSanchez** [comment]
I signed it!

**Comment by pfrisella** [comment]
Can you review and resolve the CLA issue.
If you want to check which email is associated with the commits you can view the patch file by adding 
.patch to the pull request URL: https://github.com/googledatastudio/ds-data-registry/pull/89.patch
Look at the From field, the email listed there needs to be associated with the commits. 

The "What to do if you already signed the CLA" section is helpful in troubleshooting this issue.

**Comment by AJavierSanchez** [comment]
I signed it!. 
googlecla

**Comment by pfrisella** [comment]
Thanks for contributing.

**Pull request merged**
