### PR TITLE
SEOmonitor organization and source

### PR DESCRIPTION
**Pull request by panteaandrei**

### CODE REVIEW

**Comment by panteaandrei** [comment]
I signed it!

**Comment by panteaandrei** [comment]
Hello
Any updates on this?

**Comment by pfrisella** [comment]
You need to review and resolve the CLA issue.
If you want to check which email is associated with the commits you can view the patch file by adding .patch to the pull request URL: https://github.com/googledatastudio/ds-data-registry/pull/115.patch

This isn't something I can resolve for you.

**Comment by panteaandrei** [comment]
OK. The authorized person signed it!

**Comment by panteaandrei** [comment]
Hello,
All parties have completed Google Contributor License Agreement for SC Bunt Studio SRL
Thanks

**Pull request merged**
