### PR TITLE
inSitu Sales PR

### PR DESCRIPTION
**Pull request by pgil-insitu**

### CODE REVIEW

**Comment by pgil-insitu** [comment]
Hi Google data studio team. @mendozamedina , it's been 3+ months waiting for this PR to be reviewed.  It's there anything I can do to speed up the process? are we missing something?

**Comment by mendozamedina** [comment]
Hi!
I have reviewed and approved your PR, but I'm unable to merge it because it
seems that your github user is missing a Contributor License Agreement
(CLA).
All contributors listed must be covered under a CLA for this pull request
to be merged. 📝 If you are not currently covered under a CLA, please visit
https://cla.developers.google.com/. Once you've signed, follow the "New
Contributors" link at the bottom of this page to update this check.

Can you confirm you have completed this process?

Thanks

**Review by mendozamedina — APPROVED** [review]
LGTM

**Comment by pgil-insitu** [comment]
@mendozamedina seems like your CLA is missing, can you take a look? 
image

**Comment by pgil-insitu** [comment]
@mendozamedina is there someone else that can help us with this? or am I missing something?

**Pull request merged**
