### PR TITLE
Foundant Technologies GLM-SLM Connector source

### PR DESCRIPTION
**Pull request by aszalacinski**

### CODE REVIEW

**Comment by aszalacinski** [comment]
@googlebot I signed it!

**Comment by aszalacinski** [comment]
@googlebot I signed it!

**Comment by aszalacinski** [comment]
Not quite the same; it doesn't spell out the context of the data source as this new one does.

My leadership is waiting to hear back a response on the CLA setup. He completed the form and setup the Google Group as requested but neither he nor I have received notifications that the setup is complete nor an email to register as an authorized contributor. We really would like to get that working so we can continue to work with GDS.

Any suggestions?

**Comment by pfrisella** [comment]
ok, well I would just consider whether you can update the existing data source name to spell out the context or if they are actually distinct data sources.

I don't have any visibility into the CLA process since it's automated. I suggesting reviewing https://opensource.google/docs/cla/#troubleshoot

**Comment by aszalacinski** [comment]
ok. as soon as i get permission to update, i wil update that original source. Thanks!

**Comment by aszalacinski** [comment]
Updating existing GLM source

**Pull request closed without merging**
