### PR TITLE
add salesflare org and source

### PR DESCRIPTION
**Pull request by shwetagninkarad**

### CODE REVIEW

**Review by AnuFeb — APPROVED** [review]
LGTM,Thanks for adding!

**Comment by AnuFeb** [comment]
Could you please update the branch, I will merge the change.

**Comment by AnuFeb** [comment]
Could you please update the branch, I will merge the change.

**Comment by shwetagninkarad** [comment]
I have updated the branch. Can you please merge it?

**Comment by shwetagninkarad** [comment]
@AnuFeb Could you please check and add this source and org?

**Pull request merged**
