### PR TITLE
Add gavagai organization and gavagai_explorer source

### PR DESCRIPTION
**Pull request by SergiGavagai**
Add Gavagai as valid organization and gavagai_explorer as a valid source.

### CODE REVIEW

**Comment by SergiGavagai** [comment]
Hi! We haven't received an answer yet. Is there anything missing on our end? Thanks.

**Review by AnuFeb — APPROVED** [review]
LGTM,Thanks for adding!

**Comment by AnuFeb** [comment]
Could you pls update the branch & then I will merge the changes. Thank you.

**Comment by SergiGavagai** [comment]
Done! Thanks!

**Pull request merged**
