### PR TITLE
Introduce Simplesat organization and source

### PR DESCRIPTION
**Pull request by supermetrics-kl**

### CODE REVIEW

**Review by AnuFeb — APPROVED** [review]
LGTM. Thanks for adding!

**Comment by AnuFeb** [comment]
Can you please update your branch & I will merge the change.

**Comment by supermetrics-kl** [comment]
Could you elaborate a bit, I'm not sure what to do in this case.

**Review by AnuFeb — APPROVED** [review]

**Comment by AnuFeb** [comment]
Please complete cla/google check.

**Comment by supermetrics-kl** [comment]
I have completed the CLA/Google check and it should be OK for my account/email.

There seems to be a separate issue related to your email, please see this screenshot taken from the CLA check page (https://github.com/googledatastudio/ds-data-registry/pull/666/checks?check_run_id=6710489877)
image

**Pull request closed without merging**
