### PR TITLE
Freshworks has rebranded Freshworks CRM as Freshsales

### PR DESCRIPTION
**Pull request by michaes-jivrus**
Freshworks has changed the name of  Freshworks CRM as Freshsales

### CODE REVIEW

**Comment by michaes-jivrus** [comment]
@pfrisella could you please review and merge

**Comment by michaes-jivrus** [comment]
@pfrisella could you please merge

**Comment by michaes-jivrus** [comment]
@pfrisella could you please merge

**Review by pfrisella — APPROVED** [review]
LGTM. Thanks for adding!

**Pull request merged**
