### PR TITLE
Add Capsule as organisation and source

### PR DESCRIPTION
**Pull request by tombell**
Add [Capsule](https://capsulecrm.com) as an organisation and source.

### CODE REVIEW

**Comment by tombell** [comment]
I signed it!

**Comment by tombell** [comment]
I signed it!

**Comment by tombell** [comment]
I signed it!

**Comment by tombell** [comment]
@googlebot I signed it!

**Comment by tombell** [comment]
I've signed a CLA on behalf of my employer, and we've setup that for the CLA

And it says I've already signed this CLA on behalf of my employer, apparently (see below)

screenshot 2018-10-04 at 16 57 20

However, it says it has no CLAs for me...

screenshot 2018-10-04 at 16 57 30

**Comment by philliphaines** [comment]
I signed it!

**Comment by tombell** [comment]
I signed it!

**Pull request merged**
