### PR TITLE
Added google cloud spanner as a source file

### PR DESCRIPTION
**Pull request by Tejpald3v**
Signed-off-by: Tejpald3v <tejpal@d3vtech.com>

We are fetching the data from our Google Cloud Spanner database, which is the source for custom community connector that we have built for users.

### CODE REVIEW

**Comment by Tejpald3v** [comment]
@googlebot I signed it!

**Comment by Tejpald3v** [comment]
@googlebot I signed it!

**Comment by Tejpald3v** [comment]
@googlebot I signed it!

**Review by pfrisella — CHANGES_REQUESTED** [review]
Thanks for adding this. LGTM.

**Pull request merged**
