### PR TITLE
Create sources/local_falcon

### PR DESCRIPTION
**Pull request by wurlocke**

### CODE REVIEW

**Comment by wurlocke** [comment]
Adding sources/local_falcon

**Comment by wurlocke** [comment]
@AnuFeb May I request review for approval, please. Many thanks.

**Review by AnuFeb — APPROVED** [review]
LGTM, Thanks for adding!

**Comment by AnuFeb** [comment]
Could you please update the branch, I will merge the changes.

**Comment by wurlocke** [comment]
Branch updated. Thank you very much!

**Pull request merged**
