### PR TITLE
Add Marketing Miner Data Source

### PR DESCRIPTION
**Pull request by marketingminer**

### CODE REVIEW

**Comment by marketingminer** [comment]
I have signed the CLA

**Comment by marketingminer** [comment]
We have signed corporate CLA

**Comment by pfrisella** [comment]
Can you also review and resolve the CLA issue.
If you want to check which email is associated with the commits you can view the patch file by adding .patch to the pull request URL: https://github.com/googledatastudio/ds-data-registry/pull/53.patch

**Comment by saterond** [comment]
@pfrisella I have already signed individual CLA with email ondrej.satera@gmail.com, which is associated with the commit. Also we have signed corporate CLA with our Google Group which I'm member of. I don't know what is wrong/missing..

**Comment by pfrisella** [comment]
Unfortunately I don't have visibility into what you've set up. If you're considered a Corporate Signer you need to make sure you review and confirm the points listed under the Corporate signers heading of the "What to do if you already signed the CLA" section. In the past when people have had issues they often miss some step. If you created a Google Group for the CLA then the email listed on From: line at https://github.com/googledatastudio/ds-data-registry/pull/53.patch needs to be in that group. That email also needs to be associated with your GitHub account. I suggest reviewing the Troubleshooting doc, so far in my experience it's covered any issue people have had.

**Comment by saterond** [comment]
@pfrisella I've created a new pull request from my own Github account and now it's finally ok - https://github.com/googledatastudio/ds-data-registry/pull/74

**Pull request closed without merging**
