### PR TITLE
add DataForSEO

### PR DESCRIPTION
**Pull request by gavr1l0**
add DataForSEO organization and source

### CODE REVIEW

**Comment by gavr1l0** [comment]
anybody home?

**Review by pfrisella — CHANGES_REQUESTED** [review]
Both the source and org files are empty.

**Review by gavr1l0 — COMMENTED** [review]
fix empty files

**Comment by gavr1l0** [comment]
@pfrisella review again please

**Review by pfrisella — APPROVED** [review]
LGTM. Thanks for adding!

**Pull request merged**
