### PR TITLE
Create optmyzr.json

### PR DESCRIPTION
**Pull request by HarithaDev**

### CODE REVIEW

**Comment by HarithaDev** [comment]
Optmyzr does aggregate data from AdWords, Analytics etc, but that is not being made available through the data studio connector (as there seem to be a bunch of connectors for that purpose already). The Optmyzr data studio connector will expose business intelligence data generated by the Optmyzr platform, and user activity on the Optmyzr platform.

**Comment by HarithaDev** [comment]
Could you please help us with this pull request

**Comment by HarithaDev** [comment]
Hi,

Could you please help me with this pull request.
I have replied to the email thread and in GitHub, but did not get any
response yet.
Could you please help us.

Thanks,
Haritha

**Comment by pfrisella** [comment]
Thanks for following-up.

**Comment by HarithaDev** [comment]
Thank you very much!

**Pull request merged**
