### PR TITLE
Create fda

### PR DESCRIPTION
**Pull request by everythingData-net**

### CODE REVIEW

**Comment by everythingData-net** [comment]
@pfrisella .. can you please approve this?  This one is for FDA.  Thanks you!

**Comment by everythingData-net** [comment]
HI @pfrisella would it be possible to have you look at these two commits?  I'm trying to get something into data studio.

**Review by pfrisella — CHANGES_REQUESTED** [review]
The filename is missing the json extension. It should be fda.json

**Comment by everythingData-net** [comment]
@pfrisella , can you please check again .. I updated the file

**Review by pfrisella — APPROVED** [review]
LGTM

**Pull request merged**
