### PR TITLE
Brasiliano interisk

### PR DESCRIPTION
**Pull request by WJuniorInterisk**
Adds Brasiliano Interisk source and organization;
Adds Risk Management category;

### CODE REVIEW

**Review by esantana-interisk — APPROVED** [review]

**Comment by WJuniorInterisk** [comment]
CLA submitted

**Review by WJuniorInterisk — COMMENTED** [review]
CLA submitted

**Review by WJuniorInterisk — COMMENTED** [review]
Review changes

**Review by esantana-interisk — APPROVED** [review]

**Review by WJuniorInterisk — COMMENTED** [review]
Fixed

**Comment by WJuniorInterisk** [comment]
The user @WJuniorInterisk doesn't have CLA

**Pull request closed without merging**
