### PR TITLE
Create optmyzr.json

### PR DESCRIPTION
**Pull request by HarithaDev**

### CODE REVIEW

**Comment by HarithaDev** [comment]
The CLA is already signed by my employer who is the Authorized Signer.

**Comment by minhaz** [comment]
Please review the from email address here: https://github.com/googledatastudio/ds-data-registry/pull/45.patch

This email address needs to sign the CLA / needs to be in the group for the CLA. Your current from email address is a private address. The easiest way to fix this would be to disable the email privacy option for your primary email so that your commits use your real email address. OR if you're using the command line, set your email correctly. (https://help.github.com/articles/setting-your-commit-email-address-in-git/)

**Comment by HarithaDev** [comment]
Will fix as suggested and create a new pull request

**Comment by HarithaDev** [comment]
Hi,

"Optmyzr does aggregate data from AdWords, Analytics etc, but that is not
being made available through the data studio connector (as there seem to be
a bunch of connectors for that purpose already). The Optmyzr data studio
connector will expose business intelligence data generated by the Optmyzr
platform, and user activity on the Optmyzr platform."

Thanks,
Haritha

**Pull request closed without merging**
