### PR TITLE
Local Viking organization and source added for the GDS connector

### PR DESCRIPTION
**Pull request by mikki-messer**

### CODE REVIEW

**Review by AnuFeb — APPROVED** [review]
LGTM,Thanks for adding.

**Comment by AnuFeb** [comment]
Could you please update the branch. I will merge the changes.

**Comment by mikki-messer** [comment]
> Could you please update the branch. I will merge the changes.

Done. Thanks in advance

**Comment by mikki-messer** [comment]
@AnuFeb, the branch is up-to-date and ready. Thanks!

**Comment by mikki-messer** [comment]
@AnuFeb, updated !

**Pull request merged**
