### PR TITLE
Added new source: SUPERAWESOME

### PR DESCRIPTION
**Pull request by dorin131**

### CODE REVIEW

**Comment by dorin131** [comment]
@googlebot I signed it!

**Comment by dorin131** [comment]
@googlebot I signed it!

**Comment by pfrisella** [comment]
Review the instructions above on what to check if you've already signed the CLA.
Review https://github.com/googledatastudio/ds-data-registry/pull/292.patch to make sure the email associated with the commit is the one associated with the CLA/Github username

**Comment by dorin131** [comment]
@googlebot I signed it!

**Comment by dorin131** [comment]
> Review the instructions above on what to check if you've already signed the CLA.
> Review https://github.com/googledatastudio/ds-data-registry/pull/292.patch to make sure the email associated with the commit is the one associated with the CLA/Github username

@pfrisella We have signed the CLA and the PR email matches the one from the CLA and it is associated with my GitHub account. Not sure what the issue is.

**Comment by dorin131** [comment]
@googlebot I signed it!

**Comment by dorin131** [comment]
@googlebot I signed it!

**Comment by pfrisella** [comment]
@dorin131 Corporate signer or individual signer?

**Comment by dorin131** [comment]
> @dorin131 Corporate signer or individual signer?

@pfrisella Corporate signer.
We signed last week but are still not able to merge this.

**Comment by dorin131** [comment]
@googlebot I signed it!

**Pull request closed without merging**
