### PR TITLE
Add Automated Lighthouse Check source and Foo organization

### PR DESCRIPTION
**Pull request by adamhenson**
# Summary

Adds [Automated Lighthouse Check](https://www.automated-lighthouse-check.com/) **source** and [Foo](https://www.foo.software/) **organization**.

### CODE REVIEW

**Comment by adamhenson** [comment]
@minhaz - nice work on this on this project, docs and videos. I was wondering if you could take a pass at this PR. Thanks!

**Comment by pfrisella** [comment]
This cannot be merged in until you update your branch to be up-to-date with the master branch.

**Comment by adamhenson** [comment]
@pfrisella - I've updated with `master`. Could you merge please?

**Comment by pfrisella** [comment]
Done!

**Comment by adamhenson** [comment]
Thanks

**Pull request merged**
