### PR TITLE
Kentico Xperience connector

### PR DESCRIPTION
**Pull request by kentico-matthews**
Adds data for the approval of the Kentico Xperience Partner Connector at https://github.com/Kentico/xperience-google-datastudio

### CODE REVIEW

**Review by AnuFeb — APPROVED** [review]
LGTM, Thanks for adding!

**Comment by AnuFeb** [comment]
Could you please update the branch, I will merge the branch.

**Comment by kentico-matthews** [comment]
Thank you! It should be updated now.

**Comment by AnuFeb** [comment]
Could you please update the branch again.

**Comment by kentico-matthews** [comment]
Sure thing!

**Pull request merged**
