### PR TITLE
Adding IQM Corporation data source and organization

### PR DESCRIPTION
**Pull request by alexeyiqm**
Hi,
Please add the IQM Corporation organization and data source iqm.json and iqm_reporting.json so that we could continue to publish our Data Connector for the Data Studio.
Thank you.

### CODE REVIEW

**Comment by alexeyiqm** [comment]
@googlebot I signed it

**Comment by alexeyiqm** [comment]
@googlebot I signed it!

**Comment by alexeyiqm** [comment]
@googlebot I signed it!

**Comment by alexeyiqm** [comment]
@googlebot I signed it!

**Comment by alexeyiqm** [comment]
@googlebot I signed it!

**Comment by alexeyiqm** [comment]
@googlebot I signed it!

**Comment by alexeyiqm** [comment]
@googlebot I signed it!

**Review by pfrisella — APPROVED** [review]
LGTM. Thanks for adding!

**Pull request merged**
