### PR TITLE
Add serprobot organization and source

### PR DESCRIPTION
**Pull request by multiple-digital**
Added serprobot.json files in the organizations and sources folders

### CODE REVIEW

**Comment by multiple-digital** [comment]
@googlebot I signed it!

**Comment by multiple-digital** [comment]
@googlebot I signed it!

**Comment by multiple-digital** [comment]
@googlebot I signed it!

**Comment by multiple-digital** [comment]
@googlebot I signed it!

**Review by pfrisella — APPROVED** [review]
LGTM. Thanks for adding!

**Pull request merged**
