### PR TITLE
Amplified Labs adding org, category, data source

### PR DESCRIPTION
**Pull request by astillman**
Since we're the first, please let us know if we're doing it right;)  Added ourselves as an organization, added a category for "G Suite" data (since this kind of platform usage data probably deserves its own category), and a GSUITE_FOR_GOPHER source type for data that comes from our tools.

### CODE REVIEW

**Comment by pfrisella** [comment]
Instructions on how to use the registry have been updated. Please review and make sure to consider whether the source is actually G Suite and the org is Google, if that is ultimately the source of the data.

This isn't where you register details about a connector, that is done in the connector manifest.

**Comment by astillman** [comment]
OK - I've removed AMPLIFIEDLABS from the organizations file, and modified the GOPHER_FOR_GSUITE data source to refer to GSUITE as the data type, and GOOGLE as the organization per your request.   Did I understand your request properly?

**Comment by astillman** [comment]
Confused... I signed this already...  Can you indicate whether this is still an issue?

**Comment by astillman** [comment]
Reopened - sorry for confusion.

**Comment by pfrisella** [comment]
Since this is a Google data source we'll add this one for you. I'll close this out and send a pull request. Once the change is merged you can use the new data source for your connector.

**Pull request closed without merging**
