### PR TITLE
add freshsales suite source

### PR DESCRIPTION
**Pull request by shwetagninkarad**

### CODE REVIEW

**Review by AnuFeb — APPROVED** [review]
LGTM,Thanks for adding!

**Comment by AnuFeb** [comment]
Could you please update the branch. I will merge the changes.

**Comment by AnuFeb** [comment]
Please update the branch.

**Comment by shwetagninkarad** [comment]
Updated, please check

**Comment by shwetagninkarad** [comment]
Updated, can you please check it?

**Comment by shwetagninkarad** [comment]
Can you please check, why I am getting CLA error? Only for this pull request I have this issue.

**Pull request closed without merging**
